### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ghost** [Hyphen-ated/lttp-no-music#1]
https://github.com/Hyphen-ated/lttp-no-music/assets/160071738/65659109-652a-4f38-b332-96319e22a258

Snes9x / Lunar IPS Patcher / Both the US 1.1 and Japan 1.0 versions

**Comment by ghost** [comment]
Vimm's Lair ROM works. Guess my one I had previously was just bad/corrupt. Apologies, works great now, thanks a ton for your work.

**Comment by Hyphen-ated** [comment]
I guess I oughtta specify in the readme what the base rom checksum is expected to be
